### ISSUE TITLE
Having issues installing

### ISSUE THREAD

**Issue by anirjoshi** [chrjabs/rustsat#31]
The following command to install rustsat throws an error.
```
cargo add rustsat-tools
```
The error is:
```
error: `cargo add` could not determine which package to modify. Use the `--package` option to specify a package. 
available packages: rustsat, rustsat-tools, rustsat-cadical, rustsat-kissat, rustsat-glucose, rustsat-minisat
```

I am new to using cargo and rust, is there a sequence of commands or a script to easily install this?

Also, I was hoping to use SAT-Based Multi-Objective. Raising the issue here as there doesn't seem to be an interface to raise an issue in the bitbucket repo. I tried installing the tool from `https://bitbucket.org/coreo-group/mo-prepro/src/master/`, but `make` gives me the following error:
```
error: failed to compile `rustsat v0.3.0`, intermediate artifacts can be found at `/tmp/cargo-installlwoMWj`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  none of the selected packages contains these features: all-non-conflicting, cli, did you mean: all, xz2?
make: *** [Makefile:41: opb2mcnf] Error 101
```
Hope to get this resolved soon. Thank you.

**Comment by chrjabs** [comment]
Thanks for your interest in RustSAT and our preprocessing paper. Here are some pointers that hopefully help you get everything running:

- My RustSAT project (since version `0.2.0`) is split into a couple of different crates: `rustsat`: the main library, `rustsat-<satsolver>`: interfaces for some SAT solvers, `rustsat-tools`: some small helpful tools as binaries
- `cargo add` is the command to add a package as a dependency to a project. From your error my guess is that you are running this in the root of this repository, with the goal of actually _installing_ `rustsat-tools`. To install `rustsat-tools` there is two ways. The easiest is to install the latest released version from [crates.io](https://crates.io/). For this you don't even need to clone the repository, simply run `cargo install rustsat-tools` (see [here](https://doc.rust-lang.org/cargo/commands/cargo-install.html) for more options, if you want to change where the binaries are installed or something like that). The other option is to actually build from the repository, for this run `cargo install --path tools` in the repository root.
- The [repository](https://bitbucket.org/coreo-group/mo-prepro/src/master/) related to our [preprocessing paper](http://doi.org/10.4230/LIPIcs.CP.2023.18) does not contain a single tool, but 4 MO-MaxSAT solvers that we extended with preprocessing (plus some tools we used in our experiments. Thanks for pointing out the broken Makefile, an update to RustSAT had broken the build of the `opb2mcnf` tool. That build is now fixed.
- If you were actually interested in our multi-objective MaxSAT solver called [`scuttle`](https://github.com/chrjabs/scuttle) (rather than the exact setup we used in the preprocessing paper, scuttle got an update since then), I'd recommend installing the latest release of that via `cargo install scuttle`.
