### ISSUE TITLE
Doc for solvers is broken on docs.rs

### ISSUE THREAD

**Issue by Coloquinte** [chrjabs/rustsat#46]
The solvers are currently built by cloning the corresponding git repository. This [does not work with docs.rs](https://docs.rs/crate/rustsat-kissat/0.1.3/builds/1065649), which seems to prohibit network access.

This breaks the build docs.rs for any crate that depends on one of the solvers. I'd like to make it work for my own crates.

**Comment by chrjabs** [comment]
Turns out the original PR didn't resolve this, but with #53 it should now be resolved. See the docs for kissat [here](https://docs.rs/rustsat-kissat). (The docs for cadical are still missing, but I think this is only because it tried to pull an old version of one of the other crates and failed for that reason, so with the next release the docs for that should be there as well.)

**Comment by Coloquinte** [comment]
Sorry, it seems that #[cfg(not(doc))] didn't do much actually. I like your fix :)
