### ISSUE TITLE
Support for external solvers and solver output parsing?

### ISSUE THREAD

**Issue by suomela** [chrjabs/rustsat#78]
Hi, I'm checking if there are any plans or thoughts related to these features that would be useful for us:

1. Ability to read and parse [solver output files](https://satcompetition.github.io/2024/output.html) into `rustsat::types::Assignment` objects, maybe something like `Assignment::from_solver_output(reader)` and `Assignment::from_solver_output_path(path)`.
2. Ability to run an external program as a solver. The user would just specify the path + command line arguments, and under the hood it'd invoke an external process, pipe the output of `SatInstance::to_dimacs` to the solver, check the exit status as usual (supporting also external processes that report satisfiability using [error codes 0/10/20](http://www.satcompetition.org/2004/format-solvers2004.html)) and parse the output using `Assignment::from_solver_output`.

In particular, we'd be currently interested in using multi-threaded [Gimsatul](https://github.com/arminbiere/gimsatul) as the external solver.

Here feature 1 alone would already be useful, and even if we had feature 2, we'd still like to have also feature 1, as it'd make it possible to have workflows in which e.g. SAT instance generation and solution parsing is done on one computer, while SAT solving is done in another machine.

If it helps, I can try to find someone who could contribute these features, but I'd like to first know if this makes sense, if this kind of features should be insider RustSAT or in another crate that depends on it, and if there are already some plans related to this?

**Comment by chrjabs** [comment]
Since I am developing RustSAT mainly based on what I need for my own work, there isn't really a clear roadmap for what I would want to do (except for some rough ideas tracked as issues). That being said, I agree that a more flexible option to include any solver via files/pipes sounds quite helpful, and I think it would nicely extend RustSAT. I can give this a try myself sometime, but if you need it urgently, you would need to find somebody else to contribute this.

**Comment by chrjabs** [comment]
Skimming through gimsatul a bit right now, it looks like including it via the API more directly is not as trivial as for the other solvers I've worked on so far. So even more reason to add functionality for external solvers.

**Comment by chrjabs** [comment]
Since I am not sure when I will get to this, I'll drop some notes on how I would approach this here, in case somebody else wants to pick this up. Also, if anybody is interested to do this, feel free to reach out to me to talk about this more.

Solver output parsing:
- Add `Assignment::from_vline(line: String)` function, creating an assignment from a solver output assignment line (starting with a `v `, hence dubbed v-line
- Add `Assignment::from_solver_output<R: BufRead>(reader: R)`, scanning through solver output and calling `from_vline` when a v-line is detected
- Add `Assignment::from_solver_output_path<P: AsRef<Path>>(path: P)` calling `from_solver_output`

External solver:
- Implement in `rustsat::solvers::external` and reexport main type(s) from `rustsat::solvers`
- One main type `ExternalSolver` with a `ExternalSolver::new(config: Config)` initializer
- `Config` specifies executable path, optional arguments, whether to write output to file or capture via a pipe, ...
- Run solver via `std::process::Command`
- Detect solving result from exit code or s-line and parse solution from v-line

If I get to this at one point myself, these notes should also be quite helpful.

**Comment by atimaly** [comment]
Hi @chrjabs. I think I am almost finished (okay I just miracolusly used rm -rf in the wrong directory), but still I have one problems now.
1. In the code that you have sent  the `let reader = fio::open_compressed_uncompressed_read(path).context("failed to open reader")?;` variable does not satisfy the BufRead trait and I could not solve this.

**Comment by chrjabs** [comment]
Just wrap the reader in a [`std::io::BufReader`](https://doc.rust-lang.org/stable/std/io/struct.BufReader.html). In the file parsers in the `fio` module I'm mostly doing that inside the parser function, but I should change that to not potentially buffer a reader again that is already buffered.

**Comment by chrjabs** [comment]
For completeness, note that with the just released RustSAT 0.6 you can now use [`ExternalSolver`](https://docs.rs/rustsat/latest/rustsat/solvers/external/struct.Solver.html)

**Comment by atimaly** [comment]
Great,  thank you so much!

Attila Mályusz
